version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"