version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task_management_db
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "8081:8081"
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db