version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task_management_db
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8081:8081"
    depends_on:
      - db
    command: java -jar target/task-management-system.jar